language: erlang
sudo: false

env:
  global:
    - BASELINE=ModuleSystem
    - RUN_SCRIPT="runTests.st" # .st file relative to your project's root
  matrix:
    # - SMALLTALK="SqueakTrunk"
    - SMALLTALK="Squeak5.0"
    - SMALLTALK="Squeak4.6"
    # - SMALLTALK="Squeak4.5"

addons:
  apt:
    packages:
    # 32-bit VM
    - libc6:i386
    # UUIDPlugin
    - libuuid1:i386

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -q -O filetreeCI.zip https://github.com/fniephaus/filetreeCI/archive/master.zip
   - unzip -q filetreeCI.zip
   - cd filetreeCI-*
   - export FILETREE_CI_HOME="$(pwd)"

script: $FILETREE_CI_HOME/run.sh
